Check joints
ichiro-its/tachimawari_dynamixel pull request #5
Opened 2021-08-22 03:58 UTC by maroqijalil

2021-08-23 08:23 UTC, threeal requested changes

2021-08-23 08:23 UTC, threeal commented on src/tachimawari_dynamixel/cm740.cpp
> +    std::this_thread::sleep_for(std::chrono::milliseconds(300));  // about 300msec
use literals (`300ms`), use `using namespace std::chrono_literals` first.

2021-08-23 08:23 UTC, threeal commented on src/tachimawari_dynamixel/cm740.cpp
> -bool CM740::set_baud(int baud)
Just asking, but why is it removed? and changed into a simple property setter?

2021-08-24 12:48 UTC, threeal approved these changes
Looks good to me.

2021-08-24 14:04 UTC, finesaaa approved these changes
Good 💯

2021-08-24 14:04 UTC, merged